"""sales model updates

Revision ID: 03ad0dd38fe2
Revises: ab672ffaaec4
Create Date: 2023-09-29 16:48:45.281407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03ad0dd38fe2'
down_revision = 'ab672ffaaec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
