name: Dependabot Auto-Merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.MERGE_BOT_TOKEN }}"

      - name: Enable auto-merge for eligible Dependabot PR
        if: steps.metadata.outputs.update-type != 'version-update:semver-major'
        uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ secrets.MERGE_BOT_TOKEN }}
          merge-method: squash
          use-github-auto-merge: "true"
